# DataBase Update labels
DBU = {
    '@DBU0': 'value',
    '@DBU1': '------BEGIN------',
    '@DBU2': '------END------',
    '@DBU3': 'Successfully load data from api link.',
    '@DBU4': 'No %s region %s records found in database. Proceeding to fully migration.',
    '@DBU5': 'Proceeding to update %s region %s records.',
    '@DBU6': 'No valid region specified.',
    '@DBU7': 'Api link error. Url: %s',
    '@DBU8': 'Inserted %s records in %s model table',
    '@DBU9': 'There was an error inserting data to %s. Please check log file.',
    '@DBU10': 'Updated %s records in %s model table',
    '@DBU11': 'TRUNCATE TABLE %s',
    '@DBU12': 'Truncate all auctions in %s region',
    '@DBU13': 'There was an error during truncate %s auctions table',
    '@DBU14': 'New data is not valid: %s',
    '@DBU15': 'No active realms in region: %s',
    '@DBU16': 'Realm: %s is already done.',
    '@DBU17': 'Realm: %s',
    '@DBU18': '[%s] Inserting...',
    '@DBU19': 'Error when create new auction in Realm: %s',
    '@DBU20': 'Failed to save lastModified to connected realm: %s',
    '@DBU21': '[%s] Done.',
    '@DBU22': '%s: Total: %s, Updated: %s, New: %s, Deprecated: %s',
    '@DBU23': 'Auction JSON for Realm: %s is None',
    '@DBU24': '[%s] Updating...',
    '@DBU25': 'Auction JSON for Realm: %s is None',
    '@DBU26': 'Realm %s is up to date',
    '@DBU27': 'No valid action: %s',
    '@DBU28': 'None of realm %s api link data. (url: %s)',
    '@DBU29': 'Insert %s: %s',
    '@DBU30': 'Update %s: %s',
    '@DBU31': 'Deprecate %s: %s',
    '@DBU32': '%s: There was an error during unactive',
    '@DBU33': '%s: Total: %s, New: %s, Deprecated: %s',
    '@DBU34': 'DELETE DEPRECATED AUCTIONS FROM DATABASE.',
    '@DBU35': 'Delete old %s in progress',
    '@DBU36': 'Deleted old %s',
    '@DBU37': 'DELETE DEPRECATED HOURLY TSD FROM DATABASE.',
    '@DBU38': '[%s] Inserted: %s',
    '@DBU39': 'Begin inserting TSD for %s',
    '@DBU40': 'End inserting TSD for %s'

}